# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2021-2023 The Foundation for Public Code <info@publiccode.net>

name: release-on-tag
on:
  push:
    tags:
      - "trigger-*.*.*" # tag example: trigger-0.12.1

defaults:
  run:
    shell: bash

jobs:
  release-the-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          # fetch-depth: "0" fetches whole history, we think
          fetch-depth: "0"
          ssh-key: ${{secrets.PUBLICCODE_DEPLOY_KEY}}
      - name: fetch-tags
        run: git fetch origin +refs/tags/*:refs/tags/*
      - name: echo-github-ref
        run: echo "${{ github.ref }}"
      - name: echo-trimmed-ref
        run: echo "RELEASE_TAG=$(echo ${{ github.ref }} | sed -e's@.*trigger-@@')"
      - name: trim-and-set-release-tag
        id: trim-and-set-release-tag
        run: >
          echo "RELEASE_TAG=$(echo ${{ github.ref }} | sed -e's@.*trigger-@@')"
          >> $GITHUB_OUTPUT
      - name: echo-output
        run: echo TAG ${{ steps.trim-and-set-release-tag.outputs.RELEASE_TAG }}
      - name: git-remote-v
        run: git remote -v
      - name: git-fetch
        run: git fetch --all
      - name: git-switch-release
        run: git switch release-${{ steps.trim-and-set-release-tag.outputs.RELEASE_TAG }}
      - name: git-log-5
        run: git log -5
      - name: git-merge-main
        run: git merge origin/main
      - name: install-deps
        run: >
          sudo apt-get install -y
          weasyprint
      - name: update-date
        run: script/update-changelog-date.sh
      - name: create-artifact.pdf
        run: weasyprint --presentational-hints index.html artifact.pdf
      - name: create-release-body
        run: script/release-body.sh ${{ steps.trim-and-set-release-tag.outputs.RELEASE_TAG }}
      - name: set-git-user-email
        run: git config user.email "info@publiccode.net"
      - name: set-git-user-name
        run: git config user.name "release-on-tag"
      - name: do-git-add
        run: git add CHANGELOG.md
      - name: do-git-commit
        run: git commit -m'Set CHANGELOG date'
      - name: do-git-tag
        run:  git tag ${{ steps.trim-and-set-release-tag.outputs.RELEASE_TAG }}
      - name: do-git-push
        run:  git push origin main
      - name: do-git-push-tags
        run:  git push --tags
      - name: do-git-delete-tag
        run:  git push origin :trigger-${{ steps.trim-and-set-release-tag.outputs.RELEASE_TAG }}
      - name: upload
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.trim-and-set-release-tag.outputs.RELEASE_TAG }}
          prerelease: true
          files: |
            artifact.pdf
          body_path: release.body
